/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  static const String icBack = 'assets/images/ic_back.png';
  static const String poppinsBlack = 'assets/fonts/Poppins-Black.ttf';
  static const String poppinsBlackitalic = 'assets/fonts/Poppins-BlackItalic.ttf';
  static const String poppinsBold = 'assets/fonts/Poppins-Bold.ttf';
  static const String poppinsBolditalic = 'assets/fonts/Poppins-BoldItalic.ttf';
  static const String poppinsExtrabold = 'assets/fonts/Poppins-ExtraBold.ttf';
  static const String poppinsExtrabolditalic = 'assets/fonts/Poppins-ExtraBoldItalic.ttf';
  static const String poppinsExtralight = 'assets/fonts/Poppins-ExtraLight.ttf';
  static const String poppinsExtralightitalic = 'assets/fonts/Poppins-ExtraLightItalic.ttf';
  static const String poppinsItalic = 'assets/fonts/Poppins-Italic.ttf';
  static const String poppinsLight = 'assets/fonts/Poppins-Light.ttf';
  static const String poppinsLightitalic = 'assets/fonts/Poppins-LightItalic.ttf';
  static const String poppinsMedium = 'assets/fonts/Poppins-Medium.ttf';
  static const String poppinsMediumitalic = 'assets/fonts/Poppins-MediumItalic.ttf';
  static const String poppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String poppinsSemibold = 'assets/fonts/Poppins-SemiBold.ttf';
  static const String poppinsSemibolditalic = 'assets/fonts/Poppins-SemiBoldItalic.ttf';
  static const String poppinsThin = 'assets/fonts/Poppins-Thin.ttf';
  static const String poppinsThinitalic = 'assets/fonts/Poppins-ThinItalic.ttf';
}
